name: radio_app_new
description: "VTRNK Radio Flutter application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.46 # Зафиксировано согласно логу
  just_audio_background: ^0.0.1-beta.17
  audio_service: ^0.18.18
  http: ^1.5.0
  socket_io_client: ^3.1.2
  palette_generator: ^0.3.3+7 # Discontinued, но оставляем пока
  image: ^4.5.4 # Для возможной замены palette_generator
  url_launcher: ^6.2.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  #audio_session: ^0.2.2
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  path_provider_android: ^2.2.18
  test_api: ^0.7.7

flutter:
  uses-material-design: true
  assets:
    - assets/logovtrnk.png
    - assets/ic_launcher.png
    - assets/vt-videoplaceholder.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/ic_launcher.png"